name: Build and Test
on:
  # Run on mainline branches
  push:
    branches:
      - 'master'
      - 'release-*'
      - 'go-*'
  # Run on branch/tag creation
  create:
  # Run on Pull Requests
  pull_request:

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        go: ["go1.21", "go1.22"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GOTOOLCHAIN: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version: 1.22.x
      id: go

    - name: Check gofmt
      run: diff -u <(echo -n) <(gofmt -d .)
      if: matrix.os != 'windows-latest'

    - name: Run go vet
      run: go vet $(go list ./... | grep -v /vendor/)

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -race ./...

    # Load artifacts obtained with the most recent version of Go
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: matrix.go == 'go1.22'
      with:
        path: astartectl*
        name: astartectl-snapshot-${{ matrix.os }}
