name: Examples
on:
    push:
    create:
jobs:
  build:
    name: Nix build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install nix
    - uses: nixbuild/nix-quick-install-action@v22
      with:
        nix_conf: experimental-features = nix-command flakes
    - name: nix build
      run: nix build
    - name: test result
      run: ./result/bin/astartectl help
  develop:
    name: Nix develop
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install nix
      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: nix develop
        run: nix develop
      - name: Check elixir in path
        run: elixir --version
